#!/bin/bash
# VladBingo - Customer Live View (HTML + JS)

# 1. Create the template directory
mkdir -p backend/bingo/templates

# 2. Create the Live View HTML
cat <<EOF > backend/bingo/templates/live_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VladBingo Live</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body { background-color: #0f172a; color: white; font-family: sans-serif; }
        .grid-cell { background-color: #1e293b; border: 1px solid #334155; height: 60px; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 1.2rem; border-radius: 4px; }
        .called { background-color: #eab308; color: black; transform: scale(1.05); transition: all 0.3s; box-shadow: 0 0 15px #eab308; }
    </style>
</head>
<body class="p-4">
    <div class="max-w-md mx-auto text-center">
        <h1 class="text-3xl font-bold mb-4 text-yellow-500">VladBingo Live</h1>
        <div id="status" class="mb-4 text-gray-400">Connecting to game...</div>
        
        <!-- The Bingo Grid -->
        <div class="grid grid-cols-5 gap-2 mb-6" id="bingo-grid">
            <!-- Numbers 1-75 generated by JS -->
        </div>

        <div class="bg-slate-800 p-4 rounded-lg">
            <div class="text-sm text-gray-400">Latest Number</div>
            <div id="latest-num" class="text-6xl font-black text-white">--</div>
        </div>
        
        <button id="enable-audio" class="mt-6 w-full py-3 bg-green-600 rounded-lg font-bold">Join with Audio 🔊</button>
    </div>

    <script>
        const grid = document.getElementById('bingo-grid');
        const latestDisplay = document.getElementById('latest-num');
        const status = document.getElementById('status');
        let audioEnabled = false;

        // Generate the 1-75 Grid
        for (let i = 1; i <= 75; i++) {
            const div = document.createElement('div');
            div.id = 'num-' + i;
            div.className = 'grid-cell';
            div.innerText = i;
            grid.appendChild(div);
        }

        document.getElementById('enable-audio').onclick = () => {
            audioEnabled = true;
            document.getElementById('enable-audio').style.display = 'none';
            status.innerText = "Listening for calls...";
        };

        // WebSocket connection to your Render server
        const socket = new WebSocket('wss://' + window.location.host + '/ws/game/live/');

        socket.onmessage = (e) => {
            const data = JSON.parse(e.data);
            if (data.action === 'call_number') {
                const num = data.number;
                latestDisplay.innerText = num;
                document.getElementById('num-' + num).classList.add('called');
                
                if (audioEnabled) {
                    const audio = new Audio('https://vlad-bingo-web.onrender.com/static/audio/male/B' + num + '.mp3');
                    audio.play().catch(err => console.log("Audio blocked"));
                }
            }
        };
    </script>
</body>
</html>
EOF

# 3. Update views.py to show this page
cat <<EOF > backend/bingo/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response

def live_view(request):
    return render(request, 'live_view.html')

class ChapaWebhookView(APIView):
    permission_classes = []
    def post(self, request):
        return Response({"status": "ok"})
EOF

# 4. Update urls.py to include the live route
cat <<EOF > backend/bingo/urls.py
from django.urls import path
from .views import ChapaWebhookView, live_view
urlpatterns = [
    path('chapa-webhook/', ChapaWebhookView.as_view()),
    path('live/', live_view, name='live_view'),
]
EOF

echo "✅ Customer Static Site (Live View) Added!"
