services:
  - type: web
    name: vlad-bingo-web
    env: python
    buildCommand: "./backend/build.sh"
    startCommand: "python backend/manage.py runserver 0.0.0.0:10000"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: vlad-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: vlad_db
          property: connectionString

  - type: worker
    name: vlad-bingo-bot
    env: python
    buildCommand: "./backend/build.sh"
    startCommand: "python backend/bingo/bot/main.py"

  - type: redis
    name: vlad-redis
    plan: free
    ipAllowList: []

databases:
  - name: vlad_db
    plan: free
    ipAllowList: []
